name: lotto_erp_mobile
version: 2.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0
  mobile_scanner: ^5.1.1
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
